### ISSUE TITLE
Having trouble connecting to postgres database when making migrations

### ISSUE THREAD

**Issue by connorjcantrell** [connorjcantrell/syndicate#1]
After running docker-compose:
```
version: '3.1'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  database:
    image: "postgres"
    env_file:
      - database.env # configure postgres
```
```
// database.env
POSTGRES_USER=postgres
POSTGRES_PASSWORD=secret
POSTGRES_DB=syndicate_d
```
My terminal outputs:
```
...
database_1  | 2021-01-10 21:39:13.853 UTC [1] LOG:  database system is ready to accept connections
...
adminer_1   | [Sun Jan 10 21:39:12 2021] PHP 7.4.14 Development Server (http://[::]:8080) started
```

So far so good...

Next, I attempt to make my migrations using [golang-migrate](https://github.com/golang-migrate/migrate#cli-usage) CLI ❌ :
`migrate -source file://migrations -database postgres://postgres:secret@localhost/postgres?sslmode=disable up`

```
error: pq: role "postgres" does not exist
make: *** [migrate] Error 1
```

I am having a really hard time finding information on my circumstance. Help would be greatly appreciated!

**Comment by connorjcantrell** [comment]
Laurent Arthur writes via dockercommunity.slack.com:

Your database container from the docker-compose.yml isn't exposed (no ports statement) to your host, so you're currently trying to connect to an already running container, or a pgsql service running from your host.

So you have to set ports of the database service to like "- 4432:5432", since your port 5432 is already taken (or shut down the postgres instance that is already running) so it can be reachable from your host.

**Comment by connorjcantrell** [comment]
1. Shut down the postgres instance
2. Set ports of the database to "5432:5432" (As seen below)
```
version: '3.1'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: "postgres"
    env_file:
      - database.env # configure postgres
    ports:
      - 5432:5432
```

3. Retried migration:
```
migrate -source file://migrations \
                        -database postgres://postgres:secret@localhost/postgres?sslmode=disable up
```
4. Error continues:
```
error: pq: role "postgres" does not exist
```

🤔 
Assuming I interpreted Laurents instructions correctly, this did not solve the problem.

**Comment by connorjcantrell** [comment]
Attempted to specify the port for the localhost on my [Makefile](https://github.com/connorjcantrell/syndicate/blob/main/Makefile):
```
...
migrate:
	migrate -source file://migrations \
			-database postgres://postgres:secret@localhost:5432/syndicate?sslmode=disable up
```
I was thinking this may have been the problem, but continuing to receive error:
`error: pq: role "postgres" does not exist`

**Comment by connorjcantrell** [comment]
Thank you @emilyjt, I really appreciate it!

**Comment by connorjcantrell** [comment]
One more thing @emilyjt, please excuse my naive understanding of docker, this is new to me...

I see that you added the `migrate` command inside `docker-compose.yml`. During development, I will frequently be running down and up migrations. 

Is there a way to run my migrations separately **after** my `adminer` and `db` services are running?

**Comment by emilyjt** [comment]
List of things to do:

- Make sure your database has a volume, so the data persists if your services come down.

If you do the above you could just run `docker-compose up` again to run the new migrations.

You could also open a terminal on the migrate container and run the migrations manually.

`docker container exec -it <container name/id> /bin/bash`

**Comment by emilyjt** [comment]
`docker run --rm -v D:\Development\testing\syndicate\migrations:/migrations --network syndicate_default migrate/migrate -path=/migrations/ -database postgres://user:secret@db:5432/syndicate?sslmode=disable up`

This worked for me.

You could copy and paste this and edit it to your needs.

Don't forget to make sure you **add a volume to your database**

Something like:

```
version: "3.8"

volumes:
  postgres_data: {}

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data/:Z # :Z marks the volume as private

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
```

and `Makefile`

```
.PHONY: postgres adminer migrate

compose:
	docker-compose -f docker-compose.yml up

migrate:
	docker run --rm -v ./migrations:/migrations --network syndicate_default migrate/migrate -path=/migrations/ -database postgres://user:secret@db:5432/syndicate?sslmode=disable up

migrate-down:
	docker run --rm -v ./migrations:/migrations --network syndicate_default migrate/migrate -path=/migrations/ -database postgres://user:secret@db:5432/syndicate?sslmode=disable down
```
